# Generated by Django 5.0.14 on 2026-07-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtp_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpcredential",
            name="provider",
            field=models.CharField(
                choices=[("gmail", "Gmail"), ("custom", "Custom SMTP")],
                default="gmail",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="smtpcredential",
            name="smtp_host",
            field=models.CharField(default="smtp.gmail.com", max_length=255),
        ),
        migrations.AddField(
            model_name="smtpcredential",
            name="smtp_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="smtpcredential",
            name="use_ssl",
            field=models.BooleanField(default=False),
        ),
    ]
