# Generated by Django 6.1 on 2026-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_settings', '0002_smtpcredential_provider_smtpcredential_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpcredential',
            name='auth_type',
            field=models.CharField(choices=[('PASSWORD', 'Password / App Password'), ('OAUTH2', 'OAuth 2.0')], default='PASSWORD', max_length=20),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='imap_host',
            field=models.CharField(default='imap.hostinger.com', max_length=255),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='imap_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='imap_uid_validity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='imap_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='is_monitoring_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='last_imap_uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='last_sync_status',
            field=models.CharField(choices=[('OK', 'OK'), ('AUTH_ERROR', 'Authentication Error'), ('CONNECTION_ERROR', 'Connection Error'), ('SYNCING', 'Syncing')], default='OK', max_length=30),
        ),
    ]
