# Generated by Django 5.2.15 on 2026-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
