# Generated by Django 5.0.14 on 2026-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_emaillog_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="cc",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
