# Generated by Django 6.1 on 2026-08-23 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_cc_to_email_log'),
        ('smtp_settings', '0003_smtpcredential_auth_type_smtpcredential_imap_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounced_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='replied_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='reply_status',
            field=models.CharField(choices=[('NO_REPLY', 'No Reply'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('AUTO_REPLY', 'Auto Reply/OOO'), ('UNSUBSCRIBED', 'Unsubscribed')], default='NO_REPLY', max_length=30),
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imap_uid', models.BigIntegerField()),
                ('imap_uid_validity', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('classification', models.CharField(choices=[('HUMAN_REPLY', 'Human Reply'), ('AUTO_REPLY', 'Auto Reply / Out of Office'), ('BOUNCE', 'Bounce Notification'), ('UNKNOWN', 'Unknown / System')], default='UNKNOWN', max_length=30)),
                ('sentiment', models.CharField(choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('QUESTION', 'Question / Clarification'), ('UNSUBSCRIBE', 'Unsubscribe Request'), ('NEUTRAL', 'Neutral'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='campaigns.campaign')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_replies', to='campaigns.emaillog')),
                ('smtp_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='smtp_settings.smtpcredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='BounceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bounce_type', models.CharField(choices=[('HARD_BOUNCE', 'Hard Bounce (Permanent)'), ('SOFT_BOUNCE', 'Soft Bounce (Temporary)'), ('BLOCKED', 'Blocked / Reputation'), ('SPAM', 'Spam Filtered'), ('UNKNOWN', 'Unknown Failure')], default='UNKNOWN', max_length=30)),
                ('smtp_status_code', models.CharField(blank=True, max_length=20)),
                ('diagnostic_code', models.TextField(blank=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounce_details', to='campaigns.emaillog')),
                ('inbound_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bounce_detail', to='campaigns.inboundemail')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSuppressionList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(default='Unsubscribed', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressed_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('smtp_credential', 'imap_uid_validity', 'imap_uid'), name='unique_inbound_imap_message'),
        ),
    ]
