# Generated by Django 6.1 on 2026-08-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_auto_reply_count_campaign_bounced_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
