# Generated by Django on 2026-09-02

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_inboundemail_is_read_inboundemail_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_gap_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
