# Generated by Django on 2026-09-04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_add_scheduled_at_and_send_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='attachment_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attachment_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
